sonar.projectKey=Simo-2004_TravelMate
sonar.organization=simo-2004
sonar.coverage.exclusions=**/*.dart

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=TravelMate
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8